#ifndef THERMAL_SERVICE_H
#define THERMAL_SERVICE_H

#include "vehicle_dto.h"

// --------------------------------------------------------------------------
// THERMAL MANAGEMENT MICROSERVICE
// --------------------------------------------------------------------------
class ThermalManagementService {
public:
    ThermalManagementService() = default;

    // Takes environmental inputs and heat generated by the Power Service
    ThermalTelemetryDTO updateThermals(
        const VehicleCommandDTO& inputs, 
        const PowerTelemetryDTO& powerState, 
        double dt);
        
private:
    // Internal state (Temperatures, cooling logic timers)
    ThermalTelemetryDTO state;
};

#endif